### ISSUE TITLE
fatal error: 'openssl/opensslconf.h' file not found

### ISSUE THREAD

**Issue by byproduct-of-society** [android-ia/OpenSSL#1]
vendor/intel/external/openssl/./e_os.h:62:11: fatal error: 'openssl/opensslconf.h' file not found
vendor/intel/external/openssl/apps/apps.c:126:10: fatal error: 'openssl/err.h' file not found

Additional Information : 
Have not attempted a full build yet, this is happening when issuing make -j2 kernelflinger-userdebug

**Comment by kalyankondapally** [comment]
@cmsanta @Kishore409 @shobhitka Do you guyz see the error ?

**Comment by cmsanta** [comment]
the build fails for me but for a different reason:

ninja: error: unknown target 'kernelflinger-userdebug'

**Comment by byproduct-of-society** [comment]
I'm trying to only build kernelflinger for some testing, though the build doesn't even start now since the latest manifest changes.  

the make command for kernelflinger needs to end in the build target, if we're using the example in the wiki it would be make -j2 kernelflinger-eng

**Comment by kalyankondapally** [comment]
https://github.com/android-ia/manifest/wiki#kernel-flinger-based-build

**Comment by cmsanta** [comment]
ok, well, it succeeded for me using the 'eng' target. Maybe you need to build the full build?

**Comment by kalyankondapally** [comment]
@byproduct-of-society As for the build issue can u do a repo sync and try now. We where running into some mesa3d issues

**Comment by byproduct-of-society** [comment]
@kalyankondapally  @cmsanta 
"make SPARSE_IMG=true -j2 flashfiles" was able to start to build and make it to generating a kernelflinger.efiunsigned but fails at /bin/bash: sbsign: command not found

attempting to build sbsign buy it's self generates additional openssl headers not found errors.
external/sbsigntool/src/idc.c:34:10: fatal error: 'openssl/asn1t.h' file not found
external/sbsigntool/src/fileio.c:39:10: fatal error: 'openssl/bio.h' file not found
external/sbsigntool/src/sbsign.c:45:10: fatal error: 'openssl/pem.h' file not found
external/sbsigntool/src/image.c:45:10: fatal error: 'openssl/sha.h' file not found

There was no issue building the kernelflinger standalone back on Android-5.x.x any ideas?

**Comment by kalyankondapally** [comment]
hmm https://github.com/android-ia/manifest/blob/master/include/bsp-android_ia.xml#L17 project should be pulled. Looks like u are missing some openssl dependencies, openssl-devel ?

**Comment by cmsanta** [comment]
try this: sudo apt-get install sbsigntool

**Comment by byproduct-of-society** [comment]
@kalyankondapally I have the latest libssl-dev installed on Linux Mint 17.1 Rebecca 
@cmsanta that worked to get past that build error and generated a signed kernelflinger.efi thanks.

guess i'll see if the reset of the build will finish though still curious as to why openssl repo doesn't seem to build completely. Is there a specific version of libssl-dev needed?

**Comment by byproduct-of-society** [comment]
@cmsanta @kalyankondapally After the latest sync this morning openssl, sbsign, and kernelflinger build successfully.  

Experiencing some other build issues with:   
make android_ia-efi -j2 / make SPARSE_IMG=true -j2 flashfiles 

neither command seem to build a full install able rom, and vendor.img doesn't seem to be built at all so missing kernel modules,

**Comment by kalyankondapally** [comment]
we dont have a separate vendor partition yet. Its part of system.img for now, we are in process of splitting it up

**Comment by byproduct-of-society** [comment]
@kalyankondapally hmm. i wonder whats wrong with my build machine the kernel modules are not being installed in the system.img.

Neither command listed in the wiki are building a complete system really the only thing being installed into the system.img are a couple of binaries and a few shared libs, the reset of the directory structure never gets populated no apps no frameworks......  

Jack is acting up now so i have to wipe that out and start again.

**Comment by kalyankondapally** [comment]
@byproduct-of-society Hmm Ya. Something is wrong with the build env. Can you check your <out>/system/vendor/lib/modules do you have it ?

**Comment by byproduct-of-society** [comment]
@kalyankondapally i'll let you know just did, make clobber, ccache -C, and set jack.server.max-service=1, as i only have 8GB of RAM we'll see what i get after the next build.  Thanks for all of your guys help.

**Comment by kalyankondapally** [comment]
If you update to latest code we should have a separate vendor.img file generated and partition too. Kernel modules live in vendor/lib/modules now.

**Comment by kalyankondapally** [comment]
Lets close this as issue is no more related to openssl error, u can open issue against appropriate project once u get the build done ?
